### ISSUE TITLE
Installed via snap on Fedora, now what?

### ISSUE THREAD

**Issue by davidshumway** [mmtrt/liveforspeed#3]
Installed snap and then liveforspeed: `sudo snap install liveforspeed`. Using `snap info liveforspeed` shows the program is installed. But the program isn't available from the programs menu as well as from the command line (`$ liveforspeed`: `bash: liveforspeed: command not found...`). Any ideas?

**Comment by mmtrt** [comment]
Try `snap run liveforspeed`

**Comment by davidshumway** [comment]
Got it. Thanks!
